export const COMPARISON_RESULT_MODEL = {
    "AVG_PATIENT_DOMESTIC":"averageDomesticPatient",
     "AVG_PATIENT_INTERNATIONAL":"averageInternationalPatient",
     "CONNECTIVITY":"transportation",
     "NO_OF_BED":"numberOfBeds",
     "NO_OF_ICU_BED":"numberOfICUBeds",
     "NO_OF_OT_ROOM": "numberOfRooms",
     "PAYMENT_MODE": "paymentMode",
     "DOC_ID":"id",
     "DOC_NAME":"name",
     "DOC_SPECIALIZATION":"specialization",
     "DOC_QULIFICATION":"qulification",
     "DOC_LOCATION": "location",
     "DOC_ABOUT": "about",
     "DOC_LIST_OF_TREATMENTS": "tratementLists",
     "DOC_EDUCATION": "education",
     "SPECIALITY_1": "speciality",
     "NO_OF_YEAR_EXPERIENCE": "experience",
     "IMG_NAME": "image",
     "ENT_FULL_NM": "hospitalName",
     "RANKING":"ranking",
     "DOC_WORK_EXPERIENCE":"workExperience",
     "DOC_AWARDS":"awards",
     "DESIGNATION":"designation",
}
