 

export const TYPE = {
    COUNTRY_LIST: 'COUNTRY_LIST',
    COUNTRY_LIST_LOADER: 'COUNTRY_LIST_LOADER',
    TREATMENT_LIST: 'TREATMENT_LIST',
    TREATMENT_LIST_LOADER: 'TREATMENT_LIST_LOADER',
    TOP_HOSPITALS_BY_COUNTRY: 'TOP_HOSPITALS_BY_COUNTRY',
    TOP_HOSPITALS_BY_COUNTRY_LOADER: 'TOP_HOSPITALS_BY_COUNTRY_LOADER',
    HOSPITALS_BY_COUNTRY: 'HOSPITALS_BY_COUNTRY',
    HOSPITALS_BY_COUNTRY_LOADER: 'HOSPITALS_BY_COUNTRY_LOADER'
}

