 export const TYPE = {
    DOCTORS_LIST: 'DOCTORS_LIST',
    DOCTORS_LIST_LOADER: 'DOCTORS_LIST_LOADER',
    HOSPITAL_LIST: 'HOSPITAL_LIST',
    HOSPITAL_LIST_LOADER: 'HOSPITAL_LIST_LOADER',
    COMPARE_PRODUCT_TYPE: 'COMPARE_PRODUCT_TYPE_',
    COMPARE_PRODUCT_TYPE_HOSPITALS: 'COMPARE_PRODUCT_TYPE_HOSPITALS',
    COMPARE_PRODUCT_TYPE_DOCTORS:'COMPARE_PRODUCT_TYPE_DOCTORS',
    COMPARE_PRODUCT_TYPE_CLEANUP:'COMPARE_PRODUCT_TYPE_CLEANUP'
}

